export const DISTRESS_KEYWORDS = [
  'suicide',
  'suicider',
  'me tuer',
  'mourir',
  'en finir',
  'plus envie de vivre',
  'automutilation',
  'me faire du mal',
  'scarification',
  'overdose',
  'me pendre',
  'envie de disparaitre',
  'envie de disparaître',
  'je suis un fardeau',
  'personne ne m\'aime',
  'rien ne va plus',
  'je veux mourir',
  'j\'en peux plus',
  'j\'en ai marre de vivre',
];
